In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data=pd.read_csv(r'C:\Users\HP\Desktop\diabetes.csv')
raw_data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [3]:

df=raw_data.copy()

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [5]:
print(raw_data.shape)

(768, 9)


In [6]:
df['Pregnancies'].unique()

array([ 6,  1,  8,  0,  5,  3, 10,  2,  4,  7,  9, 11, 13, 15, 17, 12, 14],
      dtype=int64)

In [7]:
sorted(df['Pregnancies'].unique())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17]

In [8]:
Pregnancies_columns=pd.get_dummies(df['Pregnancies'].unique())

In [9]:
Pregnancies_columns=pd.get_dummies(df['Pregnancies'],drop_first=True)

In [10]:
df.columns.values

array(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
       'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype=object)

In [11]:
df=df.drop(['Pregnancies'],axis=1)
df

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0        148             72             35        0  33.6   
1         85             66             29        0  26.6   
2        183             64              0        0  23.3   
3         89             66             23       94  28.1   
4        137             40             35      168  43.1   
..       ...            ...            ...      ...   ...   
763      101             76             48      180  32.9   
764      122             70             27        0  36.8   
765      121             72             23      112  26.2   
766      126             60              0        0  30.1   
767       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 8 columns]

In [12]:
pregnant=Pregnancies_columns.loc[:,1:8].max(axis=1)
not_pregnant=Pregnancies_columns.loc[:,9:].max(axis=1)

In [13]:
df=pd.concat([df,pregnant,not_pregnant],axis=1)
df

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0        148             72             35        0  33.6   
1         85             66             29        0  26.6   
2        183             64              0        0  23.3   
3         89             66             23       94  28.1   
4        137             40             35      168  43.1   
..       ...            ...            ...      ...   ...   
763      101             76             48      180  32.9   
764      122             70             27        0  36.8   
765      121             72             23      112  26.2   
766      126             60              0        0  30.1   
767       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  0  1  
0                       0.627   50        1  1  0  
1                       0.351   31        0  1  0  
2                       0.672   32        1  1  0  
3                       0.167   21        0  1  0  
4                       2.288   33        1  0  0  
..                        ...  ...      ... .. ..  
763                     0.171   63        0  0  1  
764                     0.340   27        0  1  0  
765                     0.245   30        0  1  0  
766                     0.349   47        1  1  0  
767                     0.315   23        0  1  0  

[768 rows x 10 columns]

In [14]:
df.columns.values

array(['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
       'DiabetesPedigreeFunction', 'Age', 'Outcome', 0, 1], dtype=object)

In [15]:
columns_names=(['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
       'DiabetesPedigreeFunction', 'Age', 'Outcome', 'pregnant', 'not_pregnant'])


In [16]:
df.columns=columns_names
df.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             72             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3       89             66             23       94  28.1   
4      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  pregnant  not_pregnant  
0                     0.627   50        1         1             0  
1                     0.351   31        0         1             0  
2                     0.672   32        1         1             0  
3                     0.167   21        0         1             0  
4                     2.288   33        1         0             0

In [17]:
columns_names_reordered=(['pregnant', 'not_pregnant','Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
       'DiabetesPedigreeFunction', 'Age', 'Outcome', ])

In [18]:
df=df[columns_names_reordered]
df.head(3)

pregnant  not_pregnant  Glucose  BloodPressure  SkinThickness  Insulin  \
0         1             0      148             72             35        0   
1         1             0       85             66             29        0   
2         1             0      183             64              0        0   

    BMI  DiabetesPedigreeFunction  Age  Outcome  
0  33.6                     0.627   50        1  
1  26.6                     0.351   31        0  
2  23.3                     0.672   32        1

In [19]:
df['Glucose'].median()

117.0

In [20]:
df['Glucose'].unique()

array([148,  85, 183,  89, 137, 116,  78, 115, 197, 125, 110, 168, 139,
       189, 166, 100, 118, 107, 103, 126,  99, 196, 119, 143, 147,  97,
       145, 117, 109, 158,  88,  92, 122, 138, 102,  90, 111, 180, 133,
       106, 171, 159, 146,  71, 105, 101, 176, 150,  73, 187,  84,  44,
       141, 114,  95, 129,  79,   0,  62, 131, 112, 113,  74,  83, 136,
        80, 123,  81, 134, 142, 144,  93, 163, 151,  96, 155,  76, 160,
       124, 162, 132, 120, 173, 170, 128, 108, 154,  57, 156, 153, 188,
       152, 104,  87,  75, 179, 130, 194, 181, 135, 184, 140, 177, 164,
        91, 165,  86, 193, 191, 161, 167,  77, 182, 157, 178,  61,  98,
       127,  82,  72, 172,  94, 175, 195,  68, 186, 198, 121,  67, 174,
       199,  56, 169, 149,  65, 190], dtype=int64)

In [21]:
sorted(df['Glucose'].unique())

[0,
 44,
 56,
 57,
 61,
 62,
 65,
 67,
 68,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 186,
 187,
 188,
 189,
 190,
 191,
 193,
 194,
 195,
 196,
 197,
 198,
 199]

In [22]:
Glucose_columns=pd.get_dummies(df['Glucose'])

In [23]:
Glucose_columns=pd.get_dummies(df['Glucose'],drop_first=True)

In [24]:
df.columns.values

array(['pregnant', 'not_pregnant', 'Glucose', 'BloodPressure',
       'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction',
       'Age', 'Outcome'], dtype=object)

In [25]:
df=df.drop(['Glucose'],axis=1)

In [26]:
low_glucose=Glucose_columns.loc[:,1:117].max(axis=1)
high_glucose=Glucose_columns.loc[:,117:].max(axis=1)

In [27]:
df=pd.concat([df,low_glucose,high_glucose],axis=1)
df


pregnant  not_pregnant  BloodPressure  SkinThickness  Insulin   BMI  \
0           1             0             72             35        0  33.6   
1           1             0             66             29        0  26.6   
2           1             0             64              0        0  23.3   
3           1             0             66             23       94  28.1   
4           0             0             40             35      168  43.1   
..        ...           ...            ...            ...      ...   ...   
763         0             1             76             48      180  32.9   
764         1             0             70             27        0  36.8   
765         1             0             72             23      112  26.2   
766         1             0             60              0        0  30.1   
767         1             0             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  0  1  
0                       0.627   50        1  0  1  
1                       0.351   31        0  1  0  
2                       0.672   32        1  0  1  
3                       0.167   21        0  1  0  
4                       2.288   33        1  0  1  
..                        ...  ...      ... .. ..  
763                     0.171   63        0  1  0  
764                     0.340   27        0  0  1  
765                     0.245   30        0  0  1  
766                     0.349   47        1  0  1  
767                     0.315   23        0  1  0  

[768 rows x 11 columns]

In [28]:
df.columns.values

array(['pregnant', 'not_pregnant', 'BloodPressure', 'SkinThickness',
       'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome', 0,
       1], dtype=object)

In [29]:
columns_names=(['pregnant', 'not_pregnant', 'BloodPressure', 'SkinThickness',
       'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome', 'low_glucose',
       'high_glucose'])

In [30]:
df.columns=columns_names


In [31]:
columns_names_reordered=(['pregnant', 'not_pregnant','low_glucose','high_glucose', 'BloodPressure', 'SkinThickness',
       'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome', ])

In [32]:
df=df[columns_names_reordered]
df.head(3)

pregnant  not_pregnant  low_glucose  high_glucose  BloodPressure  \
0         1             0            0             1             72   
1         1             0            1             0             66   
2         1             0            0             1             64   

   SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome  
0             35        0  33.6                     0.627   50        1  
1             29        0  26.6                     0.351   31        0  
2              0        0  23.3                     0.672   32        1

In [33]:
df['BloodPressure'].median()

72.0

In [34]:
df['BloodPressure'].unique()

array([ 72,  66,  64,  40,  74,  50,   0,  70,  96,  92,  80,  60,  84,
        30,  88,  90,  94,  76,  82,  75,  58,  78,  68, 110,  56,  62,
        85,  86,  48,  44,  65, 108,  55, 122,  54,  52,  98, 104,  95,
        46, 102, 100,  61,  24,  38, 106, 114], dtype=int64)

In [35]:
sorted(df['BloodPressure'].unique())

[0,
 24,
 30,
 38,
 40,
 44,
 46,
 48,
 50,
 52,
 54,
 55,
 56,
 58,
 60,
 61,
 62,
 64,
 65,
 66,
 68,
 70,
 72,
 74,
 75,
 76,
 78,
 80,
 82,
 84,
 85,
 86,
 88,
 90,
 92,
 94,
 95,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 114,
 122]

In [36]:
bloodpressure_columns=pd.get_dummies(df['BloodPressure'])

In [37]:
bloodpressure_columns=pd.get_dummies(df['BloodPressure'],drop_first=True)

In [38]:
df.columns.values

array(['pregnant', 'not_pregnant', 'low_glucose', 'high_glucose',
       'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
       'DiabetesPedigreeFunction', 'Age', 'Outcome'], dtype=object)

In [39]:
df=df.drop(['BloodPressure'],axis=1)

In [40]:
low_bloodpressure=bloodpressure_columns.loc[:,1:72].max(axis=1)
high_bloodpressure=bloodpressure_columns.loc[:,73:].max(axis=1)

In [41]:
df=pd.concat([df,low_bloodpressure,high_bloodpressure],axis=1)
df.head(3)

pregnant  not_pregnant  low_glucose  high_glucose  SkinThickness  Insulin  \
0         1             0            0             1             35        0   
1         1             0            1             0             29        0   
2         1             0            0             1              0        0   

    BMI  DiabetesPedigreeFunction  Age  Outcome  0  1  
0  33.6                     0.627   50        1  1  0  
1  26.6                     0.351   31        0  1  0  
2  23.3                     0.672   32        1  1  0

In [42]:
df.columns.values

array(['pregnant', 'not_pregnant', 'low_glucose', 'high_glucose',
       'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction',
       'Age', 'Outcome', 0, 1], dtype=object)

In [43]:
columns_names=(['pregnant', 'not_pregnant', 'low_glucose', 'high_glucose',
       'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction',
       'Age', 'Outcome', 'low_bloodpressure', 'high_bloodpressure'])

In [44]:
df.columns=columns_names

In [45]:
columns_names_reordered=(['pregnant', 'not_pregnant', 'low_glucose', 'high_glucose',
       'low_bloodpressure', 'high_bloodpressure','SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction',
       'Age', 'Outcome', ])

In [46]:
df=df[columns_names_reordered]
df.head(3)

pregnant  not_pregnant  low_glucose  high_glucose  low_bloodpressure  \
0         1             0            0             1                  1   
1         1             0            1             0                  1   
2         1             0            0             1                  1   

   high_bloodpressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  \
0                   0             35        0  33.6                     0.627   
1                   0             29        0  26.6                     0.351   
2                   0              0        0  23.3                     0.672   

   Age  Outcome  
0   50        1  
1   31        0  
2   32        1

In [53]:
df['Outcome'].unique()

array([1, 0], dtype=int64)

In [54]:
targets=np.where(df['Outcome']>
                df['Outcome'].median(),1,0)
targets

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [55]:
df['Outcome']=targets
df.head(5)

pregnant  not_pregnant  low_glucose  high_glucose  low_bloodpressure  \
0         1             0            0             1                  1   
1         1             0            1             0                  1   
2         1             0            0             1                  1   
3         1             0            1             0                  1   
4         0             0            0             1                  1   

   high_bloodpressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  \
0                   0             35        0  33.6                     0.627   
1                   0             29        0  26.6                     0.351   
2                   0              0        0  23.3                     0.672   
3                   0             23       94  28.1                     0.167   
4                   0             35      168  43.1                     2.288   

   Age  Outcome  
0   50        1  
1   31        0  
2   32        1  
3   21        0  
4   33        1

In [56]:
targets.sum()/targets.shape[0]

0.3489583333333333

In [60]:
unscaled_inputs=df.iloc[:,:-1]

In [61]:
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler
class CustomScaler(BaseEstimator,TransformerMixin):
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler=StandardScaler(copy,with_mean,with_std)
        self.columns=columns
        self.mean_=None
        self.var_=None
        
    def fit(self,x,y=None):
        self.scaler.fit(x[self.columns],y)
        self.mean_=np.mean(x[self.columns])
        self.var_=np.var(x[self.columns])
        return self
        
    def transform(self,x,y=None,copy=None):
        init_col_order=x.columns
        x_scaled=pd.DataFrame(self.scaler.transform(x[self.columns]),columns=self.columns)
        x_not_scaled=x.loc[:,~x.columns.isin(self.columns)]
        return pd.concat([x_not_scaled,x_scaled],axis=1)[init_col_order]
        

In [62]:
unscaled_inputs.columns.values

array(['pregnant', 'not_pregnant', 'low_glucose', 'high_glucose',
       'low_bloodpressure', 'high_bloodpressure', 'SkinThickness',
       'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'], dtype=object)

In [63]:
columns_to_omit=['pregnant','not_pregnant','low_glucose','high_glucose','low_bloodpressure','high_bloodpressure']

In [64]:
columns_to_scale=[x for x in unscaled_inputs.columns.values]

In [65]:
diabets_scaler=CustomScaler(columns_to_scale)

In [66]:
diabets_scaler.fit(unscaled_inputs)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['pregnant', 'not_pregnant', 'low_glucose', 'high_glucose',
                      'low_bloodpressure', 'high_bloodpressure',
                      'SkinThickness', 'Insulin', 'BMI',
                      'DiabetesPedigreeFunction', 'Age'],
             copy=None, with_mean=None, with_std=None)

In [67]:
scaled_inputs=diabets_scaler.transform(unscaled_inputs)

In [68]:
scaled_inputs

pregnant  not_pregnant  low_glucose  high_glucose  low_bloodpressure  \
0    0.587374     -0.355105    -1.005222      0.989637                1.0   
1    0.587374     -0.355105     0.994805     -1.010471                1.0   
2    0.587374     -0.355105    -1.005222      0.989637                1.0   
3    0.587374     -0.355105     0.994805     -1.010471                1.0   
4   -1.702491     -0.355105    -1.005222      0.989637                1.0   
..        ...           ...          ...           ...                ...   
763 -1.702491      2.816067     0.994805     -1.010471               -1.0   
764  0.587374     -0.355105    -1.005222      0.989637                1.0   
765  0.587374     -0.355105    -1.005222      0.989637                1.0   
766  0.587374     -0.355105    -1.005222      0.989637                1.0   
767  0.587374     -0.355105     0.994805     -1.010471                1.0   

     high_bloodpressure  SkinThickness   Insulin       BMI  \
0             -0.912653       0.907270 -0.692891  0.204013   
1             -0.912653       0.530902 -0.692891 -0.684422   
2             -0.912653      -1.288212 -0.692891 -1.103255   
3             -0.912653       0.154533  0.123302 -0.494043   
4             -0.912653       0.907270  0.765836  1.409746   
..                  ...            ...       ...       ...   
763            1.095707       1.722735  0.870031  0.115169   
764           -0.912653       0.405445 -0.692891  0.610154   
765           -0.912653       0.154533  0.279594 -0.735190   
766           -0.912653      -1.288212 -0.692891 -0.240205   
767           -0.912653       0.656358 -0.692891 -0.202129   

     DiabetesPedigreeFunction       Age  
0                    0.468492  1.425995  
1                   -0.365061 -0.190672  
2                    0.604397 -0.105584  
3                   -0.920763 -1.041549  
4                    5.484909 -0.020496  
..                        ...       ...  
763                 -0.908682  2.532136  
764                 -0.398282 -0.531023  
765                 -0.685193 -0.275760  
766                 -0.371101  1.170732  
767                 -0.473785 -0.871374  

[768 rows x 11 columns]

In [69]:
scaled_inputs.shape

(768, 11)

In [70]:
from sklearn.model_selection import train_test_split

train_test_split(scaled_inputs,targets)

[     pregnant  not_pregnant  low_glucose  high_glucose  low_bloodpressure  \
 667 -1.702491      2.816067     0.994805     -1.010471                1.0   
 277 -1.702491     -0.355105     0.994805     -1.010471                1.0   
 111  0.587374     -0.355105    -1.005222      0.989637                1.0   
 506 -1.702491     -0.355105    -1.005222      0.989637               -1.0   
 601  0.587374     -0.355105     0.994805     -1.010471               -1.0   
 ..        ...           ...          ...           ...                ...   
 333 -1.702491      2.816067     0.994805     -1.010471               -1.0   
 598  0.587374     -0.355105    -1.005222      0.989637               -1.0   
 24  -1.702491      2.816067    -1.005222      0.989637               -1.0   
 356  0.587374     -0.355105    -1.005222      0.989637                1.0   
 335 -1.702491     -0.355105    -1.005222      0.989637               -1.0   
 
      high_bloodpressure  SkinThickness   Insulin       BMI  \

In [71]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)
print(x_train.shape,y_train.shape)

(614, 11) (614,)


In [72]:
print(x_test.shape,y_test.shape)

(154, 11) (154,)


In [73]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [74]:
reg=LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [75]:
reg.score(x_train,y_train)

0.7671009771986971

In [76]:
model_outputs=reg.predict(x_train)
model_outputs==y_train

array([ True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True, False, False,  True,  True,
        True,  True, False, False,  True,  True, False, False,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,

In [77]:
reg.intercept_

array([-0.82606117])

In [78]:
reg.coef_

array([[ 0.03237268,  0.33542971, -1.23474761, -0.4403304 , -0.74265999,
        -0.87360367, -0.04205214, -0.04319709,  0.76697459,  0.33230982,
         0.32072772]])

In [79]:
feature_name=unscaled_inputs.columns.values

In [80]:
summary_table=pd.DataFrame(columns=['feature_name'],data=feature_name)
summary_table['coefficient']=np.transpose(reg.coef_)
summary_table

feature_name  coefficient
0                   pregnant     0.032373
1               not_pregnant     0.335430
2                low_glucose    -1.234748
3               high_glucose    -0.440330
4          low_bloodpressure    -0.742660
5         high_bloodpressure    -0.873604
6              SkinThickness    -0.042052
7                    Insulin    -0.043197
8                        BMI     0.766975
9   DiabetesPedigreeFunction     0.332310
10                       Age     0.320728

In [81]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

feature_name  coefficient
0                  Intercept    -0.826061
1                   pregnant     0.032373
2               not_pregnant     0.335430
3                low_glucose    -1.234748
4               high_glucose    -0.440330
5          low_bloodpressure    -0.742660
6         high_bloodpressure    -0.873604
7              SkinThickness    -0.042052
8                    Insulin    -0.043197
9                        BMI     0.766975
10  DiabetesPedigreeFunction     0.332310
11                       Age     0.320728

In [82]:
summary_table['Odds_ratio']=np.exp(summary_table.coefficient)
summary_table

feature_name  coefficient  Odds_ratio
0                  Intercept    -0.826061    0.437770
1                   pregnant     0.032373    1.032902
2               not_pregnant     0.335430    1.398541
3                low_glucose    -1.234748    0.290908
4               high_glucose    -0.440330    0.643824
5          low_bloodpressure    -0.742660    0.475846
6         high_bloodpressure    -0.873604    0.417445
7              SkinThickness    -0.042052    0.958820
8                    Insulin    -0.043197    0.957723
9                        BMI     0.766975    2.153242
10  DiabetesPedigreeFunction     0.332310    1.394185
11                       Age     0.320728    1.378130

In [83]:
summary_table.sort_values('Odds_ratio',ascending=False)

feature_name  coefficient  Odds_ratio
9                        BMI     0.766975    2.153242
2               not_pregnant     0.335430    1.398541
10  DiabetesPedigreeFunction     0.332310    1.394185
11                       Age     0.320728    1.378130
1                   pregnant     0.032373    1.032902
7              SkinThickness    -0.042052    0.958820
8                    Insulin    -0.043197    0.957723
4               high_glucose    -0.440330    0.643824
5          low_bloodpressure    -0.742660    0.475846
0                  Intercept    -0.826061    0.437770
6         high_bloodpressure    -0.873604    0.417445
3                low_glucose    -1.234748    0.290908

In [84]:
reg.score(x_test,y_test)

0.6753246753246753

In [85]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba

array([[0.62319638, 0.37680362],
       [0.52507184, 0.47492816],
       [0.8140431 , 0.1859569 ],
       [0.85914083, 0.14085917],
       [0.76483539, 0.23516461],
       [0.82336825, 0.17663175],
       [0.75810948, 0.24189052],
       [0.74604628, 0.25395372],
       [0.25618228, 0.74381772],
       [0.62350327, 0.37649673],
       [0.28665195, 0.71334805],
       [0.33606648, 0.66393352],
       [0.41909112, 0.58090888],
       [0.90856391, 0.09143609],
       [0.71112784, 0.28887216],
       [0.7344425 , 0.2655575 ],
       [0.97074076, 0.02925924],
       [0.78031459, 0.21968541],
       [0.5642758 , 0.4357242 ],
       [0.31621727, 0.68378273],
       [0.90457313, 0.09542687],
       [0.92136461, 0.07863539],
       [0.78798791, 0.21201209],
       [0.72219596, 0.27780404],
       [0.41343711, 0.58656289],
       [0.90086264, 0.09913736],
       [0.37670751, 0.62329249],
       [0.9668989 , 0.0331011 ],
       [0.55612211, 0.44387789],
       [0.55271419, 0.44728581],
       [0.

In [86]:
predicted_proba.shape

(154, 2)

In [87]:
predicted_proba[:,1]

array([0.37680362, 0.47492816, 0.1859569 , 0.14085917, 0.23516461,
       0.17663175, 0.24189052, 0.25395372, 0.74381772, 0.37649673,
       0.71334805, 0.66393352, 0.58090888, 0.09143609, 0.28887216,
       0.2655575 , 0.02925924, 0.21968541, 0.4357242 , 0.68378273,
       0.09542687, 0.07863539, 0.21201209, 0.27780404, 0.58656289,
       0.09913736, 0.62329249, 0.0331011 , 0.44387789, 0.44728581,
       0.83440061, 0.17498223, 0.7226141 , 0.27069335, 0.63781549,
       0.88315691, 0.3984095 , 0.28356006, 0.25725464, 0.75764304,
       0.54386407, 0.34648215, 0.58583737, 0.11850245, 0.22267524,
       0.61425994, 0.20314771, 0.48767316, 0.52114149, 0.20998797,
       0.32555757, 0.41803385, 0.7238691 , 0.25928521, 0.88957407,
       0.11297973, 0.13010949, 0.87211307, 0.08818775, 0.07038318,
       0.44313797, 0.40856843, 0.28946841, 0.41891865, 0.38318443,
       0.46747528, 0.23852901, 0.08408914, 0.05286451, 0.2282868 ,
       0.04201983, 0.38986607, 0.18263824, 0.30940317, 0.80677